apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: statusholder
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 8080
    ingresses:
        - https://statusholder.dev-fss-pub.nais.io
    replicas:
        min: 1
        max: 1
    azure:
        application:
            enabled: true

    accessPolicy:
        inbound:
            rules:
                - application: portal
                  namespace: navdig
                  cluster: dev-gcp
        outbound:
            rules:
                - application: portal
                  namespace: navdig
                  cluster: dev-gcp

