apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: statusholder
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 8080
    ingresses:
        - https://statusholder.prod-fss-pub.nais.io
        - https://statusholder.intern.nav.no
    replicas:
        min: 1
        max: 1
accessPolicy:
    inbound:
        rules:
            - application: statuspoll
              namespace: navdig
              cluster: prod-gcp
            - application: portalserver
              namespace: navdig
              cluster: prod-gcp
