apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: statusholder
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 8080
    ingresses:
        - https://statusholder.dev.intern.nav.no
        - https://statusholder.dev-fss-pub.nais.io
    replicas:
        min: 1
        max: 1
    env:
        - name: TENANT
          value: nav.no
        - name: ENV
          value: dev
    azure:
        application:
            enabled: true

    accessPolicy:
        inbound:
            rules:
                - application: portalserver
                  namespace: navdig
                  cluster: dev-gcp
                - application: onpremstatuspoll
                  namespace: navdig
                  cluster: dev-fss
        outbound:
            rules:
                - application: portalserver
                  namespace: navdig
                  cluster: dev-gcp

