apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: statusholder
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 8080
    ingresses:
        - http://statusholder.intern.nav.no
    replicas:
        min: 1
        max: 1

